### ISSUE TITLE
TypeError Uh oh! Path must be a string. Received undefined

### ISSUE THREAD

**Issue by miqmago** [alunny/node-xcode#109]
When removing custom frameworks from cordova it raises this error:

```
Error: TypeError: Uh oh!
Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at searchPathForFile (/Volumes/DATA/apps/testApp/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:1517:24)
    at pbxProject.removeFromFrameworkSearchPaths (/Volumes/DATA/apps/testApp/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:1035:20)
    at pbxProject.removeFramework (/Volumes/DATA/apps/testApp/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:307:14)
    at uninstall (/Volumes/DATA/apps/testApp/platforms/ios/cordova/lib/plugman/pluginHandlers.js:112:41)
    at Object.process (/Volumes/DATA/apps/testApp/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Plugman.removePlugin (/Volumes/DATA/apps/testApp/platforms/ios/cordova/lib/plugman/Plugman.js:125:20)
    at Api.removePlugin (/Volumes/DATA/apps/testApp/platforms/ios/cordova/Api.js:220:40)
    at handleUninstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/uninstall.js:333:6)
```

How to reproduce:
- Create a cordova project with ios platform
- Run `$ cordova plugin add cordova-admob`
- Run `$ cordova plugin rm cordova-admob`

`cordova-admob` depends on `cordova-libgoogleadmobads` which has a custom framework (admob sdk). When uninstalling this dependency, it crashes.

**Comment by miqmago** [comment]
Hmm.. I see that the version cordova is using is 0.8.4.

Could be that it has already been resolved? How could this be notified to cordova to update this dependency?

**Comment by imhotep** [comment]
I haven't been able to reproduce this issue.
@miqmago you can log an issue in Cordova's [jira](https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel)
