### ISSUE TITLE
Unable to  read xcode(8.2.1) project 

### ISSUE THREAD

**Issue by wajahatch888** [alunny/node-xcode#121]
I am using following code to read xcode project and add one header file But it fails.

`var xcode = require('xcode'),
    fs = require('fs'),
    projectPath = '/Users/Wajahat/Desktop/Test-iOS/app/Test.xcodepro',
    myProj = xcode.project(projectPath);

// parsing is async, in a different process
myProj.parse(function (err) {
    myProj.addHeaderFile('foo.h');
   fs.writeFileSync(projectPath, myProj.writeSync());
    console.log('new project written');
});`

I am getting following error

TypeError: Cannot read property 'project' of undefined
    at pbxProject.createPbxGroup (/Users/Wajahat/Desktop/electron-quick-start-master/node_modules/node-xcode-opifex/lib/pbxProject.js:450:27)
    at pbxProject.<anonymous> (/Users/Wajahat/Desktop/electron-quick-start-master/xcodetest.js:13:9)
    at emitOne (events.js:96:13)
    at pbxProject.emit (events.js:188:7)
    at pbxProject.<anonymous> (/Users/Wajahat/Desktop/electron-quick-start-master/node_modules/node-xcode-opifex/lib/pbxProject.js:28:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Someone on suggested to add `myProj.parseSync()` before adding header file but i get following error.

fs.js:731
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at pbxProject.parseSync (/Users/Wajahat/Desktop/electron-quick-start-master/node_modules/node-xcode-opifex/lib/pbxProject.js:44:28)
    at Object.<anonymous> (/Users/Wajahat/Desktop/electron-quick-start-master/xcodetest.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by hypery2k** [comment]
try first to parse, e.g.
```
var xcodeProject = xcode.project(projectPath);
xcodeProject.parseSync();
var buildPhase = xcodeProject.addBuildPhase(...
```

**Comment by imhotep** [comment]
@hypery2k apologies for the slow reply. You need to specify a group to add the header to otherwise it your header is added to a group named "Plugins" which you probably don't have in your project?

```Javascript
myProj.addHeader(path, opt, group)
```
