### ISSUE TITLE
"Cannot read property 'path' of null" on Xcode 7

### ISSUE THREAD

**Issue by felipesabino** [alunny/node-xcode#69]
Created a dummy project on Xcode 7 and tried running the example on Readme gives me the error bellow.

I tried adding a log to see what the `group` variable valuer was inside `pbxProject.js:977` and it is `Plugins` and `project.pbxGroupByName(group)` is indeed returning `null`.

```
/Users/xyz/node-xcode/node_modules/xcode/lib/pbxProject.js:977
    if (project.pbxGroupByName(group).path)
                                     ^
TypeError: Cannot read property 'path' of null
    at correctForPath (/Users/xyz/node-xcode/node_modules/xcode/lib/pbxProject.js:977:38)
    at correctForPluginsPath (/Users/xyz/node-xcode/node_modules/xcode/lib/pbxProject.js:962:12)
    at pbxProject.addPluginFile (/Users/xyz/node-xcode/node_modules/xcode/lib/pbxProject.js:88:5)
    at pbxProject.addHeaderFile (/Users/xyz/node-xcode/node_modules/xcode/lib/pbxProject.js:137:17)
    at pbxProject.<anonymous> (/Users/xyz/node-xcode/index.js:14:12)
    at pbxProject.emit (events.js:110:17)
    at pbxProject.<anonymous> (/Users/xyz/node-xcode/node_modules/xcode/lib/pbxProject.js:30:18)
    at ChildProcess.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

**Comment by mroswald** [comment]
this is a duplicate of #31
