### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by grabbou** [alunny/node-xcode#97]
```
TypeError: Cannot read property 'replace' of undefined
        at unquoted (node_modules/xcode/lib/pbxFile.js:67:16)
        at detectGroup (node_modules/xcode/lib/pbxFile.js:104:39)
        at new pbxFile (node_modules/xcode/lib/pbxFile.js:173:18)
```

That used to work. Turns out the reason is that `self = this` before passing to detectGroup points to a global object.

**Comment by bestander** [comment]
@imhotep, could you please release 0.8.9 with that fix?

**Comment by imhotep** [comment]
@bestander done
